### ISSUE TITLE
Browsersync Issue

### ISSUE THREAD

**Issue by potsmodern** [sparanoid/almace-scaffolding#7] opened 2015-08-29 03:51 UTC
```javascript
        open: true
        browser: [
          "safari",
          "firefox"
        ]
        notify: true
```
This doesn't work but

```javascript
        open: true
        browser: [
          "firefox"
        ]
        notify: true
```

Works. Please fix this.

**Comment by sparanoid** [comment] 2015-08-30 11:20
@potsmodern cannot reproduce this issue, can you provide more information?

**Comment by sparanoid** [comment] 2015-09-09 07:29
Closing as no further discussion. @potsmodern open it again if required.

**Closed by sparanoid** 2015-09-09 07:29 UTC
Labels: invalid, question
